<?php

namespace resource\api\rdstation;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-27 at 10:34:38.
 */
class rdstationLeadTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var rdstationLead
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new rdstationLead;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers resource\api\rdstation\rdstationLead::addLead
     * @todo   Implement testAddLead().
     */
    public function testAddLead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
